import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, it } from 'node:test';
import {
  conversationExportRevisionMetadataPath,
  conversationExportRevisionPath,
  initializeConversationWorkspace,
} from './conversationWorkspace.ts';
import { persistConversationExportArtifact } from './conversationWorkspaceExports.ts';

const CONVERSATION_ID = '11111111-2222-4333-8444-555555555555';

async function withWorkspaceRoot(fn: () => Promise<void>): Promise<void> {
  const previous = process.env.PCAD_CONVERSATIONS_DIR;
  const temp = await mkdtemp(join(tmpdir(), 'pcad-export-persist-'));
  process.env.PCAD_CONVERSATIONS_DIR = join(temp, 'conversations');
  try {
    await fn();
  } finally {
    if (previous === undefined) delete process.env.PCAD_CONVERSATIONS_DIR;
    else process.env.PCAD_CONVERSATIONS_DIR = previous;
    await rm(temp, { recursive: true, force: true });
  }
}

describe('conversation workspace exports', { concurrency: false }, () => {
  it('writes canonical revision exports with metadata and is idempotent', async () => {
    await withWorkspaceRoot(async () => {
      await initializeConversationWorkspace({
        conversationId: CONVERSATION_ID,
        type: 'parametric',
      });

      const bytes = new TextEncoder().encode('solid cube\nendsolid cube\n');
      const first = await persistConversationExportArtifact({
        conversationId: CONVERSATION_ID,
        format: 'stl',
        revision: 3,
        codeSha256: 'a'.repeat(64),
        bytes,
      });
      assert.equal(first.revision, 3);
      assert.equal(first.format, 'stl');
      assert.equal(first.written, true);
      assert.equal(
        await readFile(
          conversationExportRevisionPath(CONVERSATION_ID, 'stl', 3),
          'utf8',
        ),
        'solid cube\nendsolid cube\n',
      );

      const metadata = JSON.parse(
        await readFile(
          conversationExportRevisionMetadataPath(CONVERSATION_ID, 'stl', 3),
          'utf8',
        ),
      ) as {
        revision: number;
        format: string;
        codeSha256: string;
        byteLength: number;
      };
      assert.equal(metadata.revision, 3);
      assert.equal(metadata.format, 'stl');
      assert.equal(metadata.codeSha256, 'a'.repeat(64));
      assert.equal(metadata.byteLength, bytes.byteLength);

      const second = await persistConversationExportArtifact({
        conversationId: CONVERSATION_ID,
        format: 'stl',
        revision: 3,
        codeSha256: 'a'.repeat(64),
        bytes,
      });
      assert.equal(second.written, false);
      assert.equal(second.artifactSha256, first.artifactSha256);
    });
  });

  it('atomically replaces the canonical export when regenerated bytes change', async () => {
    await withWorkspaceRoot(async () => {
      await initializeConversationWorkspace({
        conversationId: CONVERSATION_ID,
        type: 'parametric',
      });

      await persistConversationExportArtifact({
        conversationId: CONVERSATION_ID,
        format: 'dxf',
        revision: 2,
        codeSha256: 'b'.repeat(64),
        bytes: new TextEncoder().encode('DXF-A'),
      });
      const replaced = await persistConversationExportArtifact({
        conversationId: CONVERSATION_ID,
        format: 'dxf',
        revision: 2,
        codeSha256: 'b'.repeat(64),
        bytes: new TextEncoder().encode('DXF-B'),
      });

      assert.equal(replaced.written, true);
      assert.equal(
        await readFile(
          conversationExportRevisionPath(CONVERSATION_ID, 'dxf', 2),
          'utf8',
        ),
        'DXF-B',
      );
    });
  });

  it('rejects invalid revisions at export path boundaries', () => {
    assert.throws(
      () => conversationExportRevisionPath(CONVERSATION_ID, 'stl', 0),
      /Invalid model revision/,
    );
  });
});
